"""Remove latitude and longitude columns and add state column in locations table

Revision ID: c0b2b61248c3
Revises: ba7639c1c27a
Create Date: 2023-06-11 15:39:45.913780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b2b61248c3'
down_revision = 'ba7639c1c27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
